/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examples;

import static examples.SudokuSolver.mymap;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.concurrent.atomic.AtomicInteger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingWorker;
import javax.swing.Timer;

/**
 *
 * @author rgukt
 */
public class sudoku extends javax.swing.JPanel {

    
    /**
     * Creates new form sudoku
     */
    public sudoku() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("Sudoku Solver");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel1)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 282, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    static int[][] arr=new int[9][9];
    public static void main(String[] args) throws Exception
{ 
    BufferedReader buf=new BufferedReader(new FileReader("/home/rgukt/NetBeansProjects/GUIFormExamples/src/examples/grid.txt"));
		for(int i=0;i<9;i++)
		{
			String str=buf.readLine();
			for(int j=0;j<9;j++)
			{
				arr[i][j]=Integer.parseInt(str.charAt(j)+"");
			}
		}
  
        new MyGridLayout();  

} 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
class MyGridLayout 
{  
            static ArrayList<JButton> buttonList = new ArrayList<JButton>();

JFrame f;  
static HashMap<String,Integer> mymap=new HashMap<String,Integer>();

	static int[][] arr=new int[9][9];
	static int holes=51,cou=0;

	static HashMap<Integer,HashSet> xcoord=new HashMap<Integer,HashSet>();
	static 	HashMap<Integer,HashSet> ycoord=new HashMap<Integer,HashSet>();
	static 	HashSet<String> firstrow=new HashSet<String>();
	static	HashSet<String> secondrow=new HashSet<String>();
	static	HashSet<String> thirdrow=new HashSet<String>();

	static	HashSet<String> firstcol=new HashSet<String>();
	static	HashSet<String> secondcol=new HashSet<String>();
	static	HashSet<String> thirdcol=new HashSet<String>();

	static java.util.List<String> list=new ArrayList<String>();
MyGridLayout() 
{ 
    int inde=0;
                for(int i=0;i<9;i++)
                {
                    for(int j=0;j<9;j++)
                    {
                        mymap.put(i+""+j,inde++);
                    }
                }
    f=new JFrame();    
    int c=1;
    sudoku sd=new sudoku();
    for(int i=0;i<9;i++)
    {
        for(int j=0;j<9;j++)
        {
            
            
            JButton bb=new JButton(sd.arr[i][j]+"");
            if(sd.arr[i][j]==0){
                bb.setBackground(Color.RED);
                bb.setText("");
            }
            
            buttonList.add(bb);
            c++;
            f.add(bb);
        }
    }
  
    f.setLayout(new GridLayout(9,9));  
    //setting grid layout of 3 rows and 3 columns  
  
    f.setSize(600,600);  
    f.setVisible(true); 
    for(int i=0;i<buttonList.size();i++)
    {
        final AtomicInteger frame = new AtomicInteger(0);
        JButton bb=buttonList.get(i);
        Timer delay = new Timer(1000, new ActionListener() {
            

            public void actionPerformed(ActionEvent e) {
                
            }
        });

        
    }
    try{
    callThis();
    }
    catch(Exception e)
    {
        System.out.println(e.toString());
    }
    


            
		

	
    
}
        static void callThis() throws Exception
        {
            firstrow.add("00");
		firstrow.add("03");
		firstrow.add("06");

		secondrow.add("30");
		secondrow.add("33");
		secondrow.add("36");

		thirdrow.add("60");
		thirdrow.add("63");
		thirdrow.add("66");

		firstcol.add("00");
		firstcol.add("30");
		firstcol.add("60");

		secondcol.add("03");
		secondcol.add("33");
		secondcol.add("63");

		thirdcol.add("06");
		thirdcol.add("36");
		thirdcol.add("66");




		xcoord.put(0,firstrow);
		xcoord.put(1,firstrow);
		xcoord.put(2,firstrow);

		xcoord.put(3,secondrow);
		xcoord.put(4,secondrow);
		xcoord.put(5,secondrow);

		xcoord.put(6,thirdrow);
		xcoord.put(7,thirdrow);
		xcoord.put(8,thirdrow);

		ycoord.put(0,firstcol);
		ycoord.put(1,firstcol);
		ycoord.put(2,firstcol);

		ycoord.put(3,secondcol);
		ycoord.put(4,secondcol);
		ycoord.put(5,secondcol);

		ycoord.put(6,thirdcol);
		ycoord.put(7,thirdcol);
		ycoord.put(8,thirdcol);

		BufferedReader buf=new BufferedReader(new FileReader("/home/rgukt/NetBeansProjects/GUIFormExamples/src/examples/grid.txt"));
		for(int i=0;i<9;i++)
		{
			String str=buf.readLine();
			for(int j=0;j<9;j++)
			{
				arr[i][j]=Integer.parseInt(str.charAt(j)+"");
			}
		}



		for(int i=0;i<9;i++)
		{
			for(int j=0;j<9;j++)
			{
				if(arr[i][j]==0)
				{
					list.add(i+""+j);
				}

			}
		}
                
		System.out.println(list.size());
                int index=0,flagg=0;
                sudoku sdd=new sudoku();
                while(index<list.size())
                {
                    int x=Integer.parseInt(list.get(index).charAt(0)+"");
                    int y=Integer.parseInt(list.get(index).charAt(1)+"");  
                    System.out.println(x+""+y);
                    
                    for(int ele=arr[x][y]+1;ele<=9;ele++)
                    {
                        JButton jb=MyGridLayout.buttonList.get(mymap.get(x+""+y));
                        if(arr[x][y]+1<=9 && isValid(ele,list.get(index)))
                        {
                            flagg=0;
                            System.out.println(list.get(index)+" "+ele);                            
                            jb.setText(ele+"");
                            jb.setBackground(Color.GREEN);
                            arr[x][y]=ele;
                            break;
                        }
                        else
                        {
                            jb.setBackground(Color.RED);
                            flagg=1;
                        }
                    }
                    if(index >=1 && flagg==1){
                        index--;
                        
                        arr[x][y]=0;
                    }
                    else
                        index++;
                }
		for(int i=0;i<9;i++)
			{
				for(int j=0;j<9;j++)
				{
					System.out.print(arr[i][j]+" ");
				}
				System.out.println();
			}
        }


        static boolean isValid(int ele,String pos)
        {
            int row=Integer.parseInt(pos.charAt(0)+"");
            int col=Integer.parseInt(pos.charAt(1)+"");
            if(checkRow(ele,row) && checkCol(ele,col) && checkSmallGrid(ele,pos))
            {
                return true;
            }
            return false;
        }
        private static boolean checkRow(int ele, int x) {
            for(int i=0;i<9;i++)
		{
			if(arr[x][i]==ele){
				return false;
			}
		}
            return true;
        }

        private static boolean checkCol(int ele, int y) {
            for(int i=0;i<9;i++)
		{
			if(arr[i][y]==ele){
				return false;
			}
		}
            return true;
            
        }

        private static boolean checkSmallGrid(int ele, String start){
            
                int x=Integer.parseInt(start.charAt(0)+"");
                int y=Integer.parseInt(start.charAt(1)+"");
                HashSet<Integer> temp1=ycoord.get(y);
		String posi=null;
		for(Object str:xcoord.get(x))
		{
			if(temp1.contains(str)){
				posi=str.toString();
				break;

			}
		}
		int sum=0;
		int px=Integer.parseInt(posi.charAt(0)+"");
		int py=Integer.parseInt(posi.charAt(1)+"");
                for(int i=0;i<3;i++)
                {
                    for(int j=0;j<3;j++)
                    {
                        int sx=px+i;
			int sy=py+j;
			if(arr[sx][sy]==ele){
				return false;
			}
                    }
                }
                return true;
            
        }

	
	static boolean isFilled(){
		for(int i=0;i<9;i++)
		{
			for(int j=0;j<9;j++)
			{
				if(arr[i][j]==0)
					return false;
			}
		}
		return true;
	}
}
